<?php
require_once ("../cn/connect2.php");
	$aa= $_POST['id_residente'];
	$ba= $_POST['id_usuario'];
	$ca= $_POST['ta_notaenfer'];
	$da= $_POST['fc_notaenfer'];
	$ea= $_POST['fr_notaenfer'];
	$fa= $_POST['sat_notaenfer'];
	$ga= $_POST['temp_notaenfer'];
	$ha= $_POST['gli_notaenfer'];
	$ia= $_POST['fec_notaenfer'];
	$ja= $_POST['percen_ing_notaenfer'];
	$ka= $_POST['cant_liq_notaenfer'];
	$la= $_POST['no_mic_notaenfer'];
	$ma= $_POST['no_evac_notaenfer'];
	$na= $_POST['no_panal_notaenfer'];
	$oa= $_POST['visita_notaenfer'];
	$pa= $_POST['caida_notaenfer'];
	$qa= $_POST['deam_notaenfer'];
	$ra= $_POST['bano_notaenfer'];
	$sa= $_POST['bucal_notaenfer'];
	$ta= $_POST['terap_notaenfer'];
	$ua= $_POST['evens_turno_notaenfer'];
	$va= date('Y-m-d H:i:s');
	$wa= $_POST['turno_notaenfer'];
		$sql2 = "INSERT INTO nota_enfermeria (id_residente, id_usuario, ta_notaenfer, fc_notaenfer, fr_notaenfer, sat_notaenfer, temp_notaenfer, gli_notaenfer, fec_notaenfer, percen_ing_notaenfer, cant_liq_notaenfer, no_mic_notaenfer, no_evac_notaenfer, no_panal_notaenfer, visita_notaenfer, caida_notaenfer, deam_notaenfer, bano_notaenfer, bucal_notaenfer, terap_notaenfer, evens_turno_notaenfer, feccap_notaenfer, turno_notaenfer) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
		$sav = $db2->prepare($sql2);
		$sav->bindValue(1, $aa, PDO::PARAM_INT);
    $sav->bindValue(2, $ba, PDO::PARAM_STR);
    $sav->bindValue(3, $ca, PDO::PARAM_STR);
    $sav->bindValue(4, $da, PDO::PARAM_STR);
    $sav->bindValue(5, $ea, PDO::PARAM_STR);
    $sav->bindValue(6, $fa, PDO::PARAM_STR);
    $sav->bindValue(7, $ga, PDO::PARAM_STR);
    $sav->bindValue(8, $ha, PDO::PARAM_STR);
    $sav->bindValue(9, $ia, PDO::PARAM_STR);
    $sav->bindValue(10, $ja, PDO::PARAM_STR);
    $sav->bindValue(11, $ka, PDO::PARAM_STR);
    $sav->bindValue(12, $la, PDO::PARAM_STR);
    $sav->bindValue(13, $ma, PDO::PARAM_STR);
    $sav->bindValue(14, $na, PDO::PARAM_STR);
    $sav->bindValue(15, $oa, PDO::PARAM_STR);
    $sav->bindValue(16, $pa, PDO::PARAM_STR);
    $sav->bindValue(17, $qa, PDO::PARAM_STR);
    $sav->bindValue(18, $ra, PDO::PARAM_STR);
    $sav->bindValue(19, $sa, PDO::PARAM_STR);
    $sav->bindValue(20, $ta, PDO::PARAM_STR);
    $sav->bindValue(21, $ua, PDO::PARAM_STR);
    $sav->bindValue(22, $va, PDO::PARAM_STR);
    $sav->bindValue(23, $wa, PDO::PARAM_STR);
		$sav->execute();
if($sav) {
      echo "<span class='uso'> Correcto.</span>";
  }else{
      echo "<span class='disponible'> Error desconocido, intenta nuevamente.</span>";
  } ;